apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-api
  template:
    metadata:
      labels:
        app: app-api
    spec:
      containers:
        - name: app-api
          image: local-registry.local:6007/app-api:latest
          ports:
            - containerPort: 3000